"""initial schema

Revision ID: f1ae43d7fa98
Revises:
Create Date: 2026-05-14 10:45:20.587425
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel  # noqa: F401 — generated migrations may reference SQLModel types

from alembic import op

revision: str = "f1ae43d7fa98"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "config_audit_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.Float(), nullable=False),
        sa.Column("entity_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("entity_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("action", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("changes_json", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "source",
            sqlmodel.sql.sqltypes.AutoString(),
            server_default="api",
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("config_audit_log", schema=None) as batch_op:
        batch_op.create_index(
            "idx_audit_entity", ["entity_type", "entity_id"], unique=False
        )
        batch_op.create_index("idx_audit_timestamp", ["timestamp"], unique=False)

    op.create_table(
        "dead_air_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("started_at_ms", sa.Integer(), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column("threshold_used_ms", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sqlmodel.sql.sqltypes.AutoString(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("tenant_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("dead_air_events", schema=None) as batch_op:
        batch_op.create_index("idx_dead_air_session_id", ["session_id"], unique=False)

    op.create_table(
        "guardrail_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("session_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("tenant_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("turn_index", sa.Integer(), nullable=True),
        sa.Column("category", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("action", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("context_excerpt", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "created_at",
            sqlmodel.sql.sqltypes.AutoString(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "event_type IN ('fired', 'bypassed')", name="ck_guardrail_events_event_type"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("guardrail_events", schema=None) as batch_op:
        batch_op.create_index("idx_guardrail_events_action", ["action"], unique=False)
        batch_op.create_index(
            "idx_guardrail_events_category", ["category"], unique=False
        )
        batch_op.create_index(
            "idx_guardrail_events_created_at", ["created_at"], unique=False
        )
        batch_op.create_index(
            "idx_guardrail_events_session_id", ["session_id"], unique=False
        )
        batch_op.create_index(
            "idx_guardrail_events_tenant_id", ["tenant_id"], unique=False
        )

    op.create_table(
        "latency_observations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("provider", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("modality", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("p50_ms", sa.Integer(), nullable=True),
        sa.Column("p95_ms", sa.Integer(), nullable=True),
        sa.Column("sample_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("window_start", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("window_end", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "refreshed_at",
            sqlmodel.sql.sqltypes.AutoString(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("latency_observations", schema=None) as batch_op:
        batch_op.create_index(
            "idx_latency_obs_project_provider",
            ["project_id", "provider", "modality"],
            unique=False,
        )

    op.create_table(
        "managed_models",
        sa.Column("model_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("modality", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("provider_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("model_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("display_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "default_language", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("default_voice", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "extra_config",
            sqlmodel.sql.sqltypes.AutoString(),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("enabled", sa.Integer(), server_default="1", nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.Column("updated_at", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("model_id"),
    )
    with op.batch_alter_table("managed_models", schema=None) as batch_op:
        batch_op.create_index("idx_managed_models_modality", ["modality"], unique=False)
        batch_op.create_index(
            "idx_managed_models_provider", ["provider_id"], unique=False
        )

    op.create_table(
        "managed_projects",
        sa.Column("project_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "description",
            sqlmodel.sql.sqltypes.AutoString(),
            server_default="",
            nullable=False,
        ),
        sa.Column("daily_budget", sa.Float(), server_default="0", nullable=False),
        sa.Column(
            "budget_action",
            sqlmodel.sql.sqltypes.AutoString(),
            server_default="warn",
            nullable=False,
        ),
        sa.Column("default_stack", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("stt_model", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("llm_model", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("tts_model", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "tags",
            sqlmodel.sql.sqltypes.AutoString(),
            server_default="[]",
            nullable=False,
        ),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.Column("updated_at", sa.Float(), nullable=False),
        sa.Column("branding_json", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "guardrail_policy_json", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.PrimaryKeyConstraint("project_id"),
    )
    op.create_table(
        "managed_providers",
        sa.Column("provider_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("provider_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "api_key_encrypted",
            sqlmodel.sql.sqltypes.AutoString(),
            server_default="",
            nullable=False,
        ),
        sa.Column("base_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "extra_config",
            sqlmodel.sql.sqltypes.AutoString(),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.Column("updated_at", sa.Float(), nullable=False),
        sa.Column("project", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("provider_id"),
    )
    with op.batch_alter_table("managed_providers", schema=None) as batch_op:
        batch_op.create_index(
            "idx_managed_providers_project", ["project"], unique=False
        )
        batch_op.create_index(
            "idx_managed_providers_type", ["provider_type"], unique=False
        )

    op.create_table(
        "replay_llm_tokens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("t_ms", sa.Integer(), nullable=False),
        sa.Column("payload", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "provider",
            sqlmodel.sql.sqltypes.AutoString(),
            server_default="",
            nullable=False,
        ),
        sa.Column("cost_usd", sa.Float(), nullable=True),
        sa.Column(
            "created_at",
            sqlmodel.sql.sqltypes.AutoString(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("tenant_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("replay_llm_tokens", schema=None) as batch_op:
        batch_op.create_index(
            "idx_replay_llm_session_t", ["session_id", "t_ms"], unique=False
        )

    op.create_table(
        "replay_state_snapshots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("t_ms", sa.Integer(), nullable=False),
        sa.Column("payload", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "created_at",
            sqlmodel.sql.sqltypes.AutoString(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("tenant_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("replay_state_snapshots", schema=None) as batch_op:
        batch_op.create_index(
            "idx_replay_state_session_t", ["session_id", "t_ms"], unique=False
        )

    op.create_table(
        "replay_stt_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("t_ms", sa.Integer(), nullable=False),
        sa.Column("payload", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "provider",
            sqlmodel.sql.sqltypes.AutoString(),
            server_default="",
            nullable=False,
        ),
        sa.Column("cost_usd", sa.Float(), nullable=True),
        sa.Column(
            "created_at",
            sqlmodel.sql.sqltypes.AutoString(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("tenant_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("replay_stt_events", schema=None) as batch_op:
        batch_op.create_index(
            "idx_replay_stt_session_t", ["session_id", "t_ms"], unique=False
        )

    op.create_table(
        "replay_tts_frames",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("t_ms", sa.Integer(), nullable=False),
        sa.Column("payload", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "provider",
            sqlmodel.sql.sqltypes.AutoString(),
            server_default="",
            nullable=False,
        ),
        sa.Column("cost_usd", sa.Float(), nullable=True),
        sa.Column(
            "created_at",
            sqlmodel.sql.sqltypes.AutoString(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("tenant_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("replay_tts_frames", schema=None) as batch_op:
        batch_op.create_index(
            "idx_replay_tts_session_t", ["session_id", "t_ms"], unique=False
        )

    op.create_table(
        "requests",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("timestamp", sa.Float(), nullable=False),
        sa.Column(
            "project",
            sqlmodel.sql.sqltypes.AutoString(),
            server_default="default",
            nullable=False,
        ),
        sa.Column("modality", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("model_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("provider", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("input_units", sa.Float(), nullable=True),
        sa.Column("output_units", sa.Float(), nullable=True),
        sa.Column("cost_usd", sa.Float(), nullable=True),
        sa.Column(
            "pricing_source",
            sqlmodel.sql.sqltypes.AutoString(),
            server_default="",
            nullable=False,
        ),
        sa.Column("ttfb_ms", sa.Float(), nullable=True),
        sa.Column("total_latency_ms", sa.Float(), nullable=True),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("fallback_from", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("error_message", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("metadata", sa.Text(), nullable=True),
        sa.Column("session_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("tenant_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("requests", schema=None) as batch_op:
        batch_op.create_index("idx_requests_modality", ["modality"], unique=False)
        batch_op.create_index("idx_requests_model", ["model_id"], unique=False)
        batch_op.create_index("idx_requests_project", ["project"], unique=False)
        batch_op.create_index(
            "idx_requests_project_timestamp", ["project", "timestamp"], unique=False
        )
        batch_op.create_index("idx_requests_session_id", ["session_id"], unique=False)
        batch_op.create_index("idx_requests_timestamp", ["timestamp"], unique=False)

    op.create_table(
        "sessions",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("project", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("started_at", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("ended_at", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "modalities",
            sqlmodel.sql.sqltypes.AutoString(),
            server_default="",
            nullable=False,
        ),
        sa.Column("total_cost_usd", sa.Float(), nullable=True),
        sa.Column("request_count", sa.Integer(), nullable=True),
        sa.Column("talk_time_seconds", sa.Float(), nullable=True),
        sa.Column("per_minute_cost_usd", sa.Float(), nullable=True),
        sa.Column("response_speed_p50_ms", sa.Integer(), nullable=True),
        sa.Column("response_speed_p95_ms", sa.Integer(), nullable=True),
        sa.Column("talk_over_rate", sa.Float(), nullable=True),
        sa.Column("replay_size_bytes", sa.Integer(), nullable=True),
        sa.Column("tenant_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("budget_ms", sa.Integer(), nullable=True),
        sa.Column("budget_ms_used", sa.Integer(), nullable=True),
        sa.Column("budget_overrun", sa.Integer(), nullable=True),
        sa.Column("routed_llm", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("routed_tts", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("guardrails_active", sa.Integer(), nullable=True),
        sa.Column("guardrails_bypassed", sa.Integer(), nullable=True),
        sa.Column(
            "guardrail_policy_snapshot_json",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.create_index("idx_sessions_project", ["project"], unique=False)
        batch_op.create_index("idx_sessions_started_at", ["started_at"], unique=False)

    op.create_table(
        "turns",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("turn_index", sa.Integer(), nullable=False),
        sa.Column("caller_speak_start_ms", sa.Integer(), nullable=False),
        sa.Column("caller_speak_end_ms", sa.Integer(), nullable=False),
        sa.Column("agent_speak_start_ms", sa.Integer(), nullable=True),
        sa.Column("agent_speak_end_ms", sa.Integer(), nullable=True),
        sa.Column("response_speed_ms", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sqlmodel.sql.sqltypes.AutoString(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("tenant_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("turns", schema=None) as batch_op:
        batch_op.create_index(
            "idx_turns_response_speed", ["response_speed_ms"], unique=False
        )
        batch_op.create_index("idx_turns_session_id", ["session_id"], unique=False)

    op.create_table(
        "virtual_keys",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("key_prefix", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("key_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("tenant_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("issued_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("virtual_keys", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_virtual_keys_key_prefix"), ["key_prefix"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_virtual_keys_tenant_id"), ["tenant_id"], unique=False
        )

    # Views (autogen does not detect them; preserved from the legacy
    # baseline. ``daily_costs`` rolls request rows up by day/modality/
    # model/provider; ``project_daily_costs`` adds the project axis.)
    # SQLite and Postgres differ on the day bucket
    # (date(ts,'unixepoch') vs to_char(to_timestamp(ts))) and on view DDL
    # (CREATE VIEW IF NOT EXISTS vs CREATE OR REPLACE VIEW), so the DDL is
    # dialect-branched. The SQLite branch is byte-for-byte the baseline.
    if op.get_bind().dialect.name == "postgresql":
        op.execute(
            """CREATE OR REPLACE VIEW daily_costs AS
    SELECT
        to_char(to_timestamp(timestamp) AT TIME ZONE 'UTC', 'YYYY-MM-DD') as day,
        modality,
        model_id,
        provider,
        COUNT(*) as request_count,
        SUM(cost_usd) as total_cost,
        AVG(ttfb_ms) as avg_ttfb,
        AVG(total_latency_ms) as avg_latency
    FROM requests
    GROUP BY to_char(to_timestamp(timestamp) AT TIME ZONE 'UTC', 'YYYY-MM-DD'),
             modality, model_id, provider"""
        )
        op.execute(
            """CREATE OR REPLACE VIEW project_daily_costs AS
    SELECT
        project,
        to_char(to_timestamp(timestamp) AT TIME ZONE 'UTC', 'YYYY-MM-DD') as day,
        modality,
        model_id,
        COUNT(*) as request_count,
        SUM(cost_usd) as total_cost,
        AVG(ttfb_ms) as avg_ttfb
    FROM requests
    GROUP BY project, to_char(to_timestamp(timestamp) AT TIME ZONE 'UTC', 'YYYY-MM-DD'),
             modality, model_id"""
        )
    else:
        op.execute(
            """CREATE VIEW IF NOT EXISTS daily_costs AS
    SELECT
        date(timestamp, 'unixepoch') as day,
        modality,
        model_id,
        provider,
        COUNT(*) as request_count,
        SUM(cost_usd) as total_cost,
        AVG(ttfb_ms) as avg_ttfb,
        AVG(total_latency_ms) as avg_latency
    FROM requests
    GROUP BY day, modality, model_id, provider"""
        )
        op.execute(
            """CREATE VIEW IF NOT EXISTS project_daily_costs AS
    SELECT
        project,
        date(timestamp, 'unixepoch') as day,
        modality,
        model_id,
        COUNT(*) as request_count,
        SUM(cost_usd) as total_cost,
        AVG(ttfb_ms) as avg_ttfb
    FROM requests
    GROUP BY project, day, modality, model_id"""
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
